In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
names = ['sepal-length','sepal-width','petal-length','petal-width','class']
dataset = pd.read_csv("iris05.csv")

In [43]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [44]:
x= dataset.iloc[:, :-1].values
y= dataset.iloc[:, 4].values

In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x , y, test_size = 0.40)

In [46]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [47]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [48]:
y_pred = classifier.predict(x_test)

In [49]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[19  0  0]
 [ 0 18  0]
 [ 0  4 19]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.82      1.00      0.90        18
   virginica       1.00      0.83      0.90        23

    accuracy                           0.93        60
   macro avg       0.94      0.94      0.93        60
weighted avg       0.95      0.93      0.93        60

